Bilgi_SayarUI/Components/NavbarViewComponent.cs
using BusinessLogic.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Bilgi_SayarUI.Components
{
    public class NavbarViewComponent:ViewComponent
    {

        private readonly ICategoryService _categoryService;

        public NavbarViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _categoryService.GetAll();
           
            return View(categories);

        }

    }
}

Bilgi_SayarUI/Areas/Writers/Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sayfam</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/Navbar/Navbar.css" />
    <link rel="stylesheet" href="~/css/Profile/Profile.css" />
    
    @await RenderSectionAsync("Head", false)

</head>

<body class="bg-light">
    <!--Navbar Start-->
    <div class="v-100">
        @await Component.InvokeAsync("Navbar")
    </div>
    <!--Navbar End-->
    <!--RenderBody-->
    <div class="v-100 my-3 "> @RenderBody()</div>


    <!--Script Start-->
    <script asp-append-version="true" src="~/js/Navbar/Navbar.js"></script>
    <script asp-append-version="true" src="~/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script asp-append-version="true" src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js"></script>
    <script asp-append-version="true" src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts",false)
    <!--Script End-->
</body>



</html>

Bilgi_SayarUI/Areas/Writers/Views/Shared/_Sign_Control.cshtml
@using Bilgi_SayarUI.Infrastructure.Extensions


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Editor"))
{
    



    <li class="nav-item">
        <a class="nav-link lead"
           asp-action="Logout" asp-area=""
           asp-controller="Account" asp-route-returnUrl="~/Default/Index">Çıkış Yap</a>

    </li>
}